/**
 * OMOM React Onboarding - TypeScript Type Definitions
 * Generated by Sequential Think MCP Server with Enhanced Ollama Integration
 * 
 * Features:
 * - Comprehensive type safety for onboarding flow
 * - Enhanced error handling with recovery strategies
 * - Progressive disclosure patterns
 * - Accessibility-first design
 */

// =============================================================================
// Core User & Authentication Types
// =============================================================================

export interface AuthUser {
  readonly id: string;
  readonly email: string;
  readonly role: UserRole;
  readonly permissions: Permission[];
  readonly profile: UserProfile;
  readonly onboardingStatus: OnboardingStatus;
  readonly createdAt: Date;
  readonly lastLoginAt: Date | null;
}

export type UserRole = 'admin' | 'manager' | 'operator' | 'viewer';

export interface Permission {
  readonly resource: string;
  readonly actions: ('create' | 'read' | 'update' | 'delete')[];
  readonly conditions?: Record<string, any>;
}

export interface UserProfile {
  firstName: string;
  lastName: string;
  avatar?: string;
  phone?: string;
  language: SupportedLanguage;
  timezone: string;
  preferences: UserPreferences;
}

export type SupportedLanguage = 'en' | 'pl' | 'de' | 'fr';

export interface UserPreferences {
  theme: 'light' | 'dark' | 'auto';
  notifications: NotificationPreferences;
  accessibility: AccessibilityPreferences;
  dashboard: DashboardPreferences;
}

// =============================================================================
// Onboarding Flow Types
// =============================================================================

export interface OnboardingStatus {
  readonly currentStep: number;
  readonly completedSteps: readonly string[];
  readonly isComplete: boolean;
  readonly startedAt: Date;
  readonly lastActivity: Date;
  readonly progressPercent: number;
  readonly estimatedTimeRemaining: number; // in seconds
  readonly skippedSteps: readonly string[];
}

export interface OnboardingStep {
  readonly id: string;
  readonly title: string;
  readonly description: string;
  readonly component: React.ComponentType<OnboardingStepProps>;
  readonly isOptional: boolean;
  readonly dependencies: readonly string[];
  readonly estimatedTime: number; // in seconds
  readonly helpResources: readonly HelpResource[];
  readonly validation?: OnboardingStepValidation;
  readonly analytics: StepAnalytics;
}

export interface OnboardingStepProps {
  step: OnboardingStep;
  onComplete: (data?: Record<string, any>) => void;
  onSkip?: () => void;
  onError: (error: OnboardingError) => void;
  userData: Partial<AuthUser>;
  isLoading: boolean;
}

export interface OnboardingStepValidation {
  schema: any; // Zod schema
  asyncValidators?: AsyncValidator[];
  crossFieldValidation?: CrossFieldValidator[];
}

export interface AsyncValidator {
  field: string;
  validator: (value: any) => Promise<ValidationResult>;
  debounceMs?: number;
}

export interface CrossFieldValidator {
  fields: string[];
  validator: (values: Record<string, any>) => ValidationResult;
}

export interface ValidationResult {
  isValid: boolean;
  error?: string;
  warnings?: string[];
  suggestions?: string[];
}

// =============================================================================
// Error Handling & Recovery Types
// =============================================================================

export interface OnboardingError {
  readonly type: OnboardingErrorType;
  readonly code: string;
  readonly message: string;
  readonly field?: string;
  readonly recoverable: boolean;
  readonly severity: ErrorSeverity;
  readonly retryAction?: () => Promise<void>;
  readonly helpUrl?: string;
  readonly metadata?: Record<string, any>;
  readonly timestamp: Date;
}

export type OnboardingErrorType =
  | 'validation'
  | 'network'
  | 'server'
  | 'permission'
  | 'timeout'
  | 'rate_limit'
  | 'data_conflict';

export type ErrorSeverity = 'low' | 'medium' | 'high' | 'critical';

export interface ErrorRecoveryStrategy {
  readonly type: 'retry' | 'skip' | 'fallback' | 'reload';
  readonly maxAttempts?: number;
  readonly delayMs?: number;
  readonly fallbackAction?: () => void;
  readonly userMessage: string;
}

// =============================================================================
// Form & Validation Types
// =============================================================================

export interface OnboardingFormData {
  personalInfo: PersonalInfo;
  organizationInfo: OrganizationInfo;
  preferences: UserPreferences;
  securitySettings: SecuritySettings;
  integrationSettings?: IntegrationSettings;
}

export interface PersonalInfo {
  firstName: string;
  lastName: string;
  email: string; // readonly after creation
  phone?: string;
  avatar?: File | string;
  jobTitle?: string;
  department?: string;
}

export interface OrganizationInfo {
  companyName: string;
  companySize: CompanySize;
  industry: Industry;
  address: Address;
  taxId?: string;
  website?: string;
}

export type CompanySize =
  | '1-10'
  | '11-50'
  | '51-200'
  | '201-1000'
  | '1000+';

export type Industry =
  | 'technology'
  | 'retail'
  | 'manufacturing'
  | 'healthcare'
  | 'finance'
  | 'education'
  | 'other';

export interface Address {
  street: string;
  city: string;
  state?: string;
  postalCode: string;
  country: string;
}

export interface SecuritySettings {
  twoFactorEnabled: boolean;
  passwordPolicy: PasswordPolicy;
  sessionTimeout: number; // in minutes
  allowedIpRanges?: string[];
}

export interface PasswordPolicy {
  minLength: number;
  requireNumbers: boolean;
  requireSymbols: boolean;
  requireMixedCase: boolean;
  expirationDays?: number;
}

// =============================================================================
// Notification & Communication Types
// =============================================================================

export interface NotificationPreferences {
  email: EmailNotificationSettings;
  push: PushNotificationSettings;
  sms: SmsNotificationSettings;
  inApp: InAppNotificationSettings;
}

export interface EmailNotificationSettings {
  enabled: boolean;
  frequency: NotificationFrequency;
  categories: NotificationCategory[];
  dailyDigest: boolean;
  marketingEmails: boolean;
}

export interface PushNotificationSettings {
  enabled: boolean;
  categories: NotificationCategory[];
  quietHours: QuietHours;
  soundEnabled: boolean;
}

export interface SmsNotificationSettings {
  enabled: boolean;
  categories: NotificationCategory[];
  number?: string;
}

export interface InAppNotificationSettings {
  enabled: boolean;
  categories: NotificationCategory[];
  showBadges: boolean;
  soundEnabled: boolean;
}

export type NotificationFrequency = 'immediate' | 'hourly' | 'daily' | 'weekly';

export type NotificationCategory =
  | 'orders'
  | 'inventory'
  | 'system'
  | 'security'
  | 'billing'
  | 'updates';

export interface QuietHours {
  enabled: boolean;
  startTime: string; // HH:MM format
  endTime: string; // HH:MM format
  timezone: string;
}

// =============================================================================
// Accessibility Types
// =============================================================================

export interface AccessibilityPreferences {
  screenReader: boolean;
  highContrast: boolean;
  reducedMotion: boolean;
  fontSize: FontSize;
  keyboardNavigation: boolean;
  colorBlindnessType?: ColorBlindnessType;
  audioDescriptions: boolean;
}

export type FontSize = 'small' | 'medium' | 'large' | 'extra-large';

export type ColorBlindnessType =
  | 'protanopia'
  | 'deuteranopia'
  | 'tritanopia'
  | 'achromatopsia';

// =============================================================================
// Help & Support Types
// =============================================================================

export interface HelpResource {
  readonly type: HelpResourceType;
  readonly title: string;
  readonly description?: string;
  readonly url?: string;
  readonly component?: React.ComponentType<any>;
  readonly duration?: string;
  readonly difficulty: 'beginner' | 'intermediate' | 'advanced';
  readonly tags: readonly string[];
}

export type HelpResourceType =
  | 'video'
  | 'article'
  | 'interactive-tour'
  | 'faq'
  | 'live-chat'
  | 'phone-support';

// =============================================================================
// Analytics & Tracking Types
// =============================================================================

export interface StepAnalytics {
  readonly stepId: string;
  readonly startTime: Date;
  readonly endTime?: Date;
  readonly duration?: number;
  readonly interactions: readonly UserInteraction[];
  readonly errors: readonly OnboardingError[];
  readonly helpResourcesViewed: readonly string[];
  readonly skipReason?: string;
}

export interface UserInteraction {
  readonly type: InteractionType;
  readonly elementId: string;
  readonly timestamp: Date;
  readonly metadata?: Record<string, any>;
}

export type InteractionType =
  | 'click'
  | 'focus'
  | 'input'
  | 'scroll'
  | 'hover'
  | 'keyboard';

// =============================================================================
// Dashboard & UI Preferences
// =============================================================================

export interface DashboardPreferences {
  layout: DashboardLayout;
  defaultView: DefaultView;
  widgetSettings: Record<string, WidgetSettings>;
  customizations: DashboardCustomizations;
}

export type DashboardLayout = 'compact' | 'comfortable' | 'spacious';

export type DefaultView =
  | 'orders'
  | 'inventory'
  | 'analytics'
  | 'reports'
  | 'settings';

export interface WidgetSettings {
  visible: boolean;
  position: { x: number; y: number };
  size: { width: number; height: number };
  configuration: Record<string, any>;
}

export interface DashboardCustomizations {
  colorScheme?: 'default' | 'blue' | 'green' | 'purple';
  logoUrl?: string;
  favicon?: string;
  customCss?: string;
}

// =============================================================================
// Integration & External Services
// =============================================================================

export interface IntegrationSettings {
  connectedServices: ConnectedService[];
  apiKeys: ApiKeySettings[];
  webhooks: WebhookSettings[];
  dataSync: DataSyncSettings;
}

export interface ConnectedService {
  readonly id: string;
  readonly name: string;
  readonly type: ServiceType;
  readonly status: ConnectionStatus;
  readonly connectedAt: Date;
  readonly lastSync?: Date;
  readonly configuration: Record<string, any>;
}

export type ServiceType =
  | 'crm'
  | 'erp'
  | 'payment'
  | 'shipping'
  | 'analytics'
  | 'communication';

export type ConnectionStatus =
  | 'connected'
  | 'disconnected'
  | 'error'
  | 'pending';

export interface ApiKeySettings {
  readonly id: string;
  readonly name: string;
  readonly keyPreview: string; // masked version
  readonly permissions: string[];
  readonly expiresAt?: Date;
  readonly lastUsed?: Date;
}

export interface WebhookSettings {
  readonly id: string;
  readonly url: string;
  readonly events: string[];
  readonly secret: string;
  readonly active: boolean;
  readonly retryPolicy: RetryPolicy;
}

export interface RetryPolicy {
  maxAttempts: number;
  backoffStrategy: 'linear' | 'exponential';
  delayMs: number;
}

export interface DataSyncSettings {
  autoSync: boolean;
  syncInterval: number; // in minutes
  conflictResolution: 'local' | 'remote' | 'manual';
  lastSync?: Date;
}

// =============================================================================
// Context & Hook Types
// =============================================================================

export interface OnboardingContextType {
  currentStep: OnboardingStep | null;
  allSteps: readonly OnboardingStep[];
  progress: OnboardingStatus;
  formData: Partial<OnboardingFormData>;
  errors: readonly OnboardingError[];

  // Actions
  goToStep: (stepId: string) => void;
  completeStep: (stepId: string, data?: Record<string, any>) => Promise<void>;
  skipStep: (stepId: string, reason?: string) => Promise<void>;
  updateFormData: (data: Partial<OnboardingFormData>) => void;
  handleError: (error: OnboardingError) => void;
  clearError: (errorCode: string) => void;
  restartOnboarding: () => void;

  // State
  isLoading: boolean;
  isComplete: boolean;
  canGoBack: boolean;
  canGoForward: boolean;
}

export interface UseOnboardingValidationReturn {
  control: any; // React Hook Form control
  errors: Record<string, any>;
  isValid: boolean;
  isValidating: boolean;
  validateStep: (stepId: string) => Promise<boolean>;
  validateField: (fieldName: string) => Promise<boolean>;
  getFieldError: (fieldName: string) => string | undefined;
  clearFieldError: (fieldName: string) => void;
}

// =============================================================================
// API Response Types
// =============================================================================

export interface OnboardingApiResponse<T = any> {
  success: boolean;
  data?: T;
  error?: {
    code: string;
    message: string;
    details?: Record<string, any>;
  };
  metadata?: {
    requestId: string;
    timestamp: Date;
    processingTime: number;
  };
}

export interface SaveOnboardingProgressRequest {
  stepId: string;
  formData: Partial<OnboardingFormData>;
  metadata?: Record<string, any>;
}

export interface CompleteOnboardingRequest {
  finalData: OnboardingFormData;
  analytics: StepAnalytics[];
  feedback?: UserFeedback;
}

export interface UserFeedback {
  rating: number; // 1-5
  comments?: string;
  suggestions?: string;
  wouldRecommend: boolean;
  difficulty: 'too-easy' | 'just-right' | 'too-hard';
}

// =============================================================================
// Utility Types
// =============================================================================

export type DeepPartial<T> = {
  [P in keyof T]?: T[P] extends object ? DeepPartial<T[P]> : T[P];
};

export type RequiredFields<T, K extends keyof T> = T & Required<Pick<T, K>>;

export type OptionalFields<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;

export type StepComponentProps<T = Record<string, any>> = OnboardingStepProps & {
  formData: T;
  updateFormData: (data: Partial<T>) => void;
};

// =============================================================================
// Constants & Enums
// =============================================================================

export const ONBOARDING_STORAGE_KEY = 'omom_onboarding_progress' as const;
export const ONBOARDING_VERSION = '1.0.0' as const;
export const MAX_ONBOARDING_TIME_MINUTES = 30 as const;

export const DEFAULT_STEP_TIMEOUT = 300000 as const; // 5 minutes
export const MAX_RETRY_ATTEMPTS = 3 as const;
export const VALIDATION_DEBOUNCE_MS = 500 as const;

// =============================================================================
// Type Guards
// =============================================================================

export function isValidUserRole(role: string): role is UserRole {
  return ['admin', 'manager', 'operator', 'viewer'].includes(role);
}

export function isOnboardingError(error: any): error is OnboardingError {
  return (
    typeof error === 'object' &&
    error !== null &&
    'type' in error &&
    'code' in error &&
    'message' in error
  );
}

export function isStepComplete(step: OnboardingStep, completedSteps: readonly string[]): boolean {
  return completedSteps.includes(step.id);
}

export function canAccessStep(step: OnboardingStep, completedSteps: readonly string[]): boolean {
  return step.dependencies.every(dep => completedSteps.includes(dep));
}
